version: '3'

services:
  node0:
    container_name: node0
    image: "nibiru/node"
    ports:
      - "26656-26657:26656-26657"
      - "9090:9090"
      - "1317:1317"
    environment:
      - ID=0
    volumes:
      - ./data/node0/nibid:/root/.nibid:Z
    networks:
      localnet:
        ipv4_address: 192.168.11.2

  node1:
    container_name: node1
    image: "nibiru/node"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
    volumes:
      - ./data/node1/nibid:/root/.nibid:Z
    networks:
      localnet:
        ipv4_address: 192.168.11.3

  node2:
    container_name: node2
    image: "nibiru/node"
    environment:
      - ID=2
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./data/node2/nibid:/root/.nibid:Z
    networks:
      localnet:
        ipv4_address: 192.168.11.4

  node3:
    container_name: node3
    image: "nibiru/node"
    environment:
      - ID=3
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./data/node3/nibid:/root/.nibid:Z
    networks:
      localnet:
        ipv4_address: 192.168.11.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.11.0/16
