name: chaosnet

services:
  nibiru:
    build:
      context: ../.. # nibiru project folder
      dockerfile: ./contrib/docker/chaosnet.Dockerfile # relative to context directory (i.e. nibiru project folder)
      args:
        MNEMONIC: guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host
    ports:
      - 26657:26657
      - 1317:1317
      - 9090:9090
    volumes:
      - nibid-data:/root/.nibid/data:rw

  faucet:
    restart: always
    image: ghcr.io/nibiruchain/go-faucet:latest
    environment:
      NODE: nibiru:9090
      MNEMONIC: undo donkey arena rule old portion long forget rescue post stuff normal reduce raw unable warrior method stairs valley enhance glory lens sign zero
      SEND_COINS: 11000000unibi,100000000unusd,100000000uusdt
      MAX_SEND_COINS: 110000000unibi,1000000000unusd,1000000000uusdt
    depends_on:
      nibiru:
        condition: service_started
    ports:
      - 8000:8000

  heartmonitor-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: heart-monitor
    ports:
      - 5433:5432

  heartmonitor:
    image: ghcr.io/nibiruchain/go-heartmonitor:latest
    restart: always
    command: --clean
    volumes:
      - nibid-data:/heartmonitor/.nibid/data:ro
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@heartmonitor-db:5432/heart-monitor?sslmode=disable
      - TENDERMINT_RPC_ENDPOINT=http://nibiru:26657
      - GRPC_ENDPOINT=tcp://nibiru:9090
      - GRPC_INSECURE=true
      - NO_PARTITIONS=true
      - CHAIN_DB_PATH=/heartmonitor/.nibid/data

  liquidator:
    image: ghcr.io/nibiruchain/go-heartmonitor:latest
    restart: always
    command: --liquidator
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@heartmonitor-db:5432/heart-monitor?sslmode=disable
      - TENDERMINT_RPC_ENDPOINT=http://nibiru:26657
      - GRPC_ENDPOINT=tcp://nibiru:9090
      - GRPC_INSECURE=true
      - NO_PARTITIONS=true
      - LIQUIDATOR_MNEMONIC=record damage person caution truly riot resource luxury rude guide mushroom athlete fantasy dentist friend mule depth salmon photo unfold exclude coyote idea evoke
      - LIQUIDATOR_GAS_LIMIT_INITIAL=500000
      - LIQUIDATOR_GAS_MULTIPLIER=5
      - LIQUIDATOR_GAS_MAX_ATTEMPTS=10
    depends_on:
      heartmonitor:
        condition: service_started

  graphql:
    image: ghcr.io/nibiruchain/go-heartmonitor:latest
    restart: always
    command: --graphql
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@heartmonitor-db:5432/heart-monitor?sslmode=disable
      - NO_PARTITIONS=true
    ports:
      - 5555:5555
    depends_on:
      heartmonitor:
        condition: service_started

  pricefeeder:
    image: ghcr.io/nibiruchain/pricefeeder:latest
    restart: always
    environment:
      CHAIN_ID: nibiru-localnet-0
      GRPC_ENDPOINT: nibiru:9090
      WEBSOCKET_ENDPOINT: ws://nibiru:26657/websocket
      FEEDER_MNEMONIC: empower dice proud brick treat reward pull jeans right rubber infant hamster pet foster among crush quick report rival bracket easily mouse topple absorb
      EXCHANGE_SYMBOLS_MAP: '{ "bitfinex": { "ubtc:uusd": "tBTCUSD", "ueth:uusd": "tETHUSD", "uusdt:uusd": "tUSTUSD" }, "binance": { "ubtc:uusd": "BTCUSD", "ueth:uusd": "ETHUSD", "uusdt:uusd": "USDTUSD", "uusdc:uusd": "USDCUSD", "uatom:uusd": "ATOMUSD", "ubnb:uusd": "BNBUSD", "uavax:uusd": "AVAXUSD", "usol:uusd": "SOLUSD", "uada:uusd": "ADAUSD", "ubtc:unusd": "BTCUSD", "ueth:unusd": "ETHUSD", "uusdt:unusd": "USDTUSD", "uusdc:unusd": "USDCUSD", "uatom:unusd": "ATOMUSD", "ubnb:unusd": "BNBUSD", "uavax:unusd": "AVAXUSD", "usol:unusd": "SOLUSD", "uada:unusd": "ADAUSD" } }'
      VALIDATOR_ADDRESS: nibivaloper1zaavvzxez0elundtn32qnk9lkm8kmcszuwx9jz
    depends_on:
      nibiru:
        condition: service_started

volumes:
  nibid-data:
