name: "Automatically update changelog with dependabot"
on: 
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  changelog-update:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'dependabot') || 
      ${{ any(contains(commit.author.username, 'dependabot') for commit in github.event.commits) }}
    steps: 
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NIBIRU_PM }}
          # to avoid checking out the repo in a detached state
          ref: ${{ github.head_ref }}
      # Helps keep your repository up-to-date when Dependabot updates your dependencies.
      # This step updates adds a line to the  "## Unreleased" section
      - uses: dangoslen/dependabot-changelog-helper@v3
        with:
          activationLabel: 'dependabot'
          changelogPath: './CHANGELOG.md'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated changelog - dependabot"
