name: 🧪✨ Test coverage ✨🧪

on:
  workflow_call:
  workflow_dispatch: # Runs on manual calls
  schedule: 
    - cron: "0 0 * * *" # Runs automatically every day
  pull_request:

# Allow concurrent runs on main/release branches but isolates other branches 
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true

      - name: Run all unit tests.
        run: make test-coverage-integration

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
