---
name: CosmWasm e2e contract tests

on:
  # On normal PRs or when workflow goreleaser finishes, as it gets the last release tag.
  pull_request:

# Allow concurrent runs on main/release branches but isolates other branches 
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  get-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: download release
        uses: robinraju/release-downloader@v1.8
        with:
          # uses latest (including drafts)
          # tag: ${{ steps.latest_release.outputs.release }} 
          # uses latest (excluding drafts) as tagged by GitHub
          latest: true
          fileName: "*linux_amd64.tar.gz"

      - name: unpack release
        run: |
          tar -xzf *linux_amd64.tar.gz
          rm nibid*.gz
          mv nibid* nibid || true

      - name: launch localnet
        run: |
          sh ./contrib/scripts/e2e/localnet.sh

      - name: run e2e tests
        run: |
          sh ./contrib/scripts/e2e/deploy-wasm.sh
