name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "master", "**" ]

jobs:

  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build binaries for matrixd using the Makefile
      run: make build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Run all tests.
      run: go test -v ./...


