name: Integration tests

on:
  workflow_dispatch: # Runs on manual calls
  schedule:
    - cron: "0 0 * * *" # Runs automatically every day
  pull_request:
    # paths makes the action run only when the given paths are changed
    paths: ["**.go", "**.proto", "go.mod", "go.sum"]

# Allow concurrent runs on main/release branches but isolates other branches
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  integration-tests:
    # Job that runs all tests and publishes code coverage reports.
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true

      - name: Run all integration tests.
        run: make test-coverage-integration

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
