name: Integration tests

on:
  pull_request:
    # paths makes the action run only when the given paths are changed
    paths: ["**.go", "**.proto", "go.mod", "go.sum"]

jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Run all integration tests.
        run: make test-integration
