name: Integration tests on master

# Runs on master merge only.
on:
  pull_request_review:
    types: [ submitted ]

jobs:
  integration-tests:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Run all tests.
        run: make test-integration