name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Run all integration tests.
        run: make test-integration
