name: Integration tests on master

# Runs on master merge only.
on:
  push:
    branches: ["master"]

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Run all tests.
        run: go test -v ./... -cover