# skip-coverage.yml runs when coverage.yml is skipped
name: Test Coverage

on:
  pull_request:
    # paths-ignore makes the action run when the given paths are unchanged
    # See "Handling skipped but required checks" in
    # https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
    paths-ignore: ["**.go", "**.proto", "go.mod", "go.sum"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: skip-tests
        run: |
          echo "coverage.yml skipped since Golang files were not changed."
