name: Unit Tests

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Run all unit tests.
        run: make test-unit
