name: Unit Tests

on:
  pull_request:
    paths: ["**.go", "**.proto", "go.mod", "go.sum"]

# Allow concurrent runs on main/release branches but isolates other branches 
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true

      - name: Run all unit tests.
        run: make test-coverage

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Build the nibid binary 
      run: make build
