name: Unit Tests

on:
  pull_request:
    paths: ["**.go", "**.proto", "go.mod", "go.sum"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true

      - name: Run all unit tests.
        run: make test-unit

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Build the nibid binary 
      run: make build