name: Unit Tests

# Runs on PRs only, not on master.
on:
  pull_request:
    branches: ["**"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Run all unit tests.
        run: make test-unit
